package com.cs206.g2t2.service.serviceImpl;

import com.cs206.g2t2.data.request.team.TeamCreationRequest;
import com.cs206.g2t2.data.request.team.TeamUpdateRequest;
import com.cs206.g2t2.data.response.Response;
import com.cs206.g2t2.data.response.bsTeam.SingleBsTeamResponse;
import com.cs206.g2t2.data.response.common.SuccessResponse;
import com.cs206.g2t2.exceptions.badRequest.DuplicatedTeamNameException;
import com.cs206.g2t2.exceptions.badRequest.TeamIsFullException;
import com.cs206.g2t2.exceptions.forbidden.ForbiddenException;
import com.cs206.g2t2.exceptions.notFound.*;
import com.cs206.g2t2.models.BsTeam;
import com.cs206.g2t2.models.TeamMember;
import com.cs206.g2t2.models.User;
import com.cs206.g2t2.repository.BsTeamRepository;
import com.cs206.g2t2.repository.UserRepository;
import com.cs206.g2t2.service.services.BsTeamService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.ArrayList;

@Service
@RequiredArgsConstructor
public class BsTeamServiceImpl implements BsTeamService {

    private final UserRepository userRepository;
    private final BsTeamRepository bsTeamRepository;

    private BsTeam saveAndReturnBsTeamInRepository(TeamCreationRequest request)
            throws DuplicatedTeamNameException, TeamNameNotFoundException {

        //Stores username in a variable
        String teamName = request.getTeamName();

        //Checks if Team's team name already exists in database
        if (bsTeamRepository.findByTeamName(teamName).isPresent()) {
            throw new DuplicatedTeamNameException(teamName);
        }

        //Creates bsTeam from TeamCreationRequest
        BsTeam bsTeam = BsTeam.builder()
                .teamName(request.getTeamName())
                .region(request.getRegion())
                .maximumTeamSize(request.getMaximumTeamSize())
                .imageString(null)
                .trophyRequirements(0)
                .min3v3Wins(0)
                .minDuoWins(0)
                .minSoloWins(0)
                .memberList(new ArrayList<TeamMember>())
                .build();

        //Saves bsTeam into repository
        bsTeamRepository.save(bsTeam);

        //Returns bsTeam stored in repository to caller
        return bsTeamRepository.findByTeamName(teamName).orElseThrow(() -> new TeamNameNotFoundException(teamName));
    }

    private void isOwnerOrAdminUser(User user, BsTeam bsTeam) throws ForbiddenException {
        //Finds current user from the bsTeam and check if the user is an Admin/Owner
        boolean found = false;
        for (TeamMember teamMember : bsTeam.getMemberList()) {
            if (teamMember.getUserId().equals(user.get_id()) &&
               (teamMember.getRole() == TeamMember.Role.ADMIN || teamMember.getRole() == TeamMember.Role.OWNER)) {
                found = true;
            }
        }

        //If the user is not an admin member of the team, throw new ForbiddenException
        if (!found) { throw new ForbiddenException(); }
    }

    @Override
    public Response getBsTeamByTeamId(String teamId) {

        //Finds BsTeam in bsTeamRepository by teamId
        BsTeam bsTeam = bsTeamRepository.findBy_id(teamId).orElseThrow(() -> new TeamNotFoundException(teamId));

        //Return SingleBsTeamResponse
        return SingleBsTeamResponse.builder()
                .bsTeam(bsTeam)
                .build();
    }

    @Override
    public Response createBsTeam(TeamCreationRequest request, String username) throws UsernameNotFoundException {

        //Find user from userRepository
        User user = userRepository.findByUsername(username).orElseThrow(() -> new UsernameNotFoundException(username));
        TeamMember teamMember = TeamMember.builder()
                .userId(user.get_id())
                .role(TeamMember.Role.OWNER)
                .joinDate(LocalDateTime.now())
                .build();

        //Obtains bsTeam from repository (Contains autogenerated _id)
        BsTeam bsTeam = saveAndReturnBsTeamInRepository(request);

        //Save the teamId into user's list of teamsId
        user.getTeams().add(bsTeam.get_id());

        //Save the teamMember into bsTeam
        bsTeam.getMemberList().add(teamMember);

        //Save both bsTeam and user into respective repository
        userRepository.save(user);
        bsTeamRepository.save(bsTeam);

        //Return SingleBsTeamResponse
        return SingleBsTeamResponse.builder()
                .bsTeam(bsTeam)
                .build();
    }

    @Override
    public Response updateBsTeam(TeamUpdateRequest request, String teamId, String username)
            throws UsernameNotFoundException, TeamNameNotFoundException, ForbiddenException {

        //Find Team from userRepository
        User user = userRepository.findByUsername(username).orElseThrow(() -> new UsernameNotFoundException(username));

        //Find Team from bsTeamRepository
        BsTeam bsTeam = bsTeamRepository.findBy_id(teamId)
                .orElseThrow(() -> new TeamNotFoundException(teamId));

        //Checks if current user is an admin user or owner, else throws ForbiddenException
        isOwnerOrAdminUser(user, bsTeam);

        //Perform update of all fields
        bsTeam.setTrophyRequirements(request.getTrophyRequirements());
        bsTeam.setMin3v3Wins(request.getMin3v3Wins());
        bsTeam.setMinDuoWins(request.getMinDuoWins());
        bsTeam.setMinSoloWins(request.getMinSoloWins());
        if (request.getImageString() != null) {
            bsTeam.setImageString(request.getImageString());
        }

        //Save bsTeam into teamRepository
        bsTeamRepository.save(bsTeam);

        //Return SingleBsTeamResponse
        return SingleBsTeamResponse.builder()
                .bsTeam(bsTeam)
                .build();
    }

    @Override
    public Response addMember(String username, String teamId, String memberId)
            throws UsernameNotFoundException, UserNotFoundException, TeamNameNotFoundException, TeamIsFullException {

        //Find User from userRepository
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new UsernameNotFoundException(username));

        //Find User from userRepository
        User member = userRepository.findBy_id(memberId)
                .orElseThrow(() -> new UserNotFoundException(memberId));

        //Find Team from bsTeamRepository
        BsTeam bsTeam = bsTeamRepository.findBy_id(teamId)
                .orElseThrow(() -> new TeamNotFoundException(teamId));

        //Checks if current user is an admin user or owner, else throws ForbiddenException
        isOwnerOrAdminUser(user, bsTeam);

        //Checks if current team is full already, if so throw TeamIsFullException
        if (bsTeam.getMemberList().size() == bsTeam.getMaximumTeamSize()) {
            throw new TeamIsFullException(bsTeam.getTeamName(), bsTeam.getMaximumTeamSize());
        }

        //Create TeamMember Object and add to the bsTeam as a member
        TeamMember teamMember = TeamMember.builder()
                .userId(member.get_id())
                .role(TeamMember.Role.MEMBER)
                .joinDate(LocalDateTime.now())
                .build();
        bsTeam.getMemberList().add(teamMember);

        //Add Team to members TeamList
        member.getTeams().add(teamId);

        //Save member and bsTeam into userRepository and teamRepository respectively
        bsTeamRepository.save(bsTeam);
        userRepository.save(member);

        //Return SuccessResponse
        return SuccessResponse.builder()
                .message("Team Member " + member.getUsername() + " has been added successfully into " + bsTeam.getTeamName())
                .build();
    }

    @Override
    public Response promoteMember(String username, String teamId, String memberId)
            throws UsernameNotFoundException, UserNotFoundException, TeamNameNotFoundException, MemberNotFoundException {

        //Find User from userRepository
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new UsernameNotFoundException(username));

        //Find User from userRepository
        User member = userRepository.findBy_id(memberId)
                .orElseThrow(() -> new UserNotFoundException(memberId));

        //Find Team from bsTeamRepository
        BsTeam bsTeam = bsTeamRepository.findBy_id(teamId)
                .orElseThrow(() -> new TeamNotFoundException(teamId));

        //Checks if current user is an admin user or owner, else throws ForbiddenException
        isOwnerOrAdminUser(user, bsTeam);

        //Iterates through the memberList of the bsTeam and find whether member exists in the memberList
        boolean found = false;
        for (TeamMember teamMember : bsTeam.getMemberList()) {
            if (teamMember.getUserId().equals(member.get_id())) {
                //If teamMember found, promote member and change found to true
                found = true;
                teamMember.setRole(TeamMember.Role.ADMIN);
            }
        }

        //If member cannot be found, throw new MemberNotFoundException
        if (!found) { throw new MemberNotFoundException(member.getUsername(), bsTeam.getTeamName()); }

        //Save bsTeam into teamRepository
        bsTeamRepository.save(bsTeam);

        //Return SuccessResponse
        return SuccessResponse.builder()
                .message("Team Member " + member.getUsername() + " has been promoted successfully")
                .build();
    }
}
