package com.cs206.g2t2.models.team;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.List;

@Document("team")
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class BsTeam {

    // _id stores the team's autogenerated id
    @Id
    private String _id;

    // teamCreationDate stores the date and time of the creation of the user
    private LocalDateTime teamCreationDate;

    // teamName stores the team's name
    private String teamName;

    // language stores the team's used language
    private String language;

    // region stores the team's competing region
    private String region;

    // maximumTeamSize stores the maximum number of members of the team
    private int maximumTeamSize;

    // imageString stores the S3 image link, can be null if there is no image
    private String imageString;

    // trophyRequirements stores the number of trophies that user need before joining the team
    private int trophyRequirements;

    // min3v3Wins stores the number of wins in 3v3 game mode that user needs before joining the team
    private int min3v3Wins;

    // minDuoWins stores the number of wins in 2v2 game mode that user needs before joining the team
    private int minDuoWins;

    // minSoloWins stores the number of wins in 1v1 game mode that user needs before joining the team
    private int minSoloWins;

    //memberList stores the list of members that the team has
    private List<TeamMember> memberList;
}
